package com.candleora.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class SchemaRepairRunner implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(SchemaRepairRunner.class);

    private final JdbcTemplate jdbcTemplate;

    public SchemaRepairRunner(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        addProductColumnsIfNeeded();
        addOrderColumnsIfNeeded();
        createAddressesTableIfNeeded();
        backfillProductColumns();
        backfillOrderColumns();
    }

    private void addProductColumnsIfNeeded() {
        executeSchemaUpdate("ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price DECIMAL(10,2) DEFAULT 0.00 NOT NULL");
        executeSchemaUpdate("ALTER TABLE products ADD COLUMN IF NOT EXISTS visible BOOLEAN DEFAULT TRUE NOT NULL");
    }

    private void addOrderColumnsIfNeeded() {
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_amount DECIMAL(10,2)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0.00");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code VARCHAR(64)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS alternate_phone_number VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS country VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS location_label VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancellation_reason VARCHAR(512)");
    }

    private void createAddressesTableIfNeeded() {
        executeSchemaUpdate("""
            CREATE TABLE IF NOT EXISTS addresses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                label VARCHAR(80),
                full_name VARCHAR(255) NOT NULL,
                street_address VARCHAR(255) NOT NULL,
                address_line_2 VARCHAR(255),
                city VARCHAR(120) NOT NULL,
                state VARCHAR(120) NOT NULL,
                zip_code VARCHAR(20) NOT NULL,
                country VARCHAR(120) NOT NULL,
                phone VARCHAR(40) NOT NULL,
                is_default BOOLEAN DEFAULT FALSE NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )
            """);
        executeSchemaUpdate("CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id)");
    }

    private void backfillProductColumns() {
        executeSchemaUpdate("UPDATE products SET cost_price = CAST(price * 0.58 AS DECIMAL(10,2)) WHERE cost_price IS NULL OR cost_price = 0");
        executeSchemaUpdate("UPDATE products SET visible = TRUE WHERE visible IS NULL");
    }

    private void backfillOrderColumns() {
        executeSchemaUpdate("UPDATE orders SET subtotal_amount = total_amount WHERE subtotal_amount IS NULL");
        executeSchemaUpdate("UPDATE orders SET discount_amount = 0.00 WHERE discount_amount IS NULL");
        executeSchemaUpdate("UPDATE orders SET payment_method = CASE WHEN payment_provider = 'COD' THEN 'COD' ELSE 'PHONEPE' END WHERE payment_method IS NULL");
    }

    private void executeSchemaUpdate(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (RuntimeException exception) {
            log.warn("Schema repair statement failed: {}", sql, exception);
        }
    }
}
