package com.candleora.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class SchemaRepairRunner implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(SchemaRepairRunner.class);

    private final JdbcTemplate jdbcTemplate;

    public SchemaRepairRunner(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(ApplicationArguments args) {
        addProductColumnsIfNeeded();
        addOrderColumnsIfNeeded();
        addCouponColumnsIfNeeded();
        createAddressesTableIfNeeded();
        createProductInventoryMovementsTableIfNeeded();
        createProductReviewsTableIfNeeded();
        backfillProductColumns();
        backfillOrderColumns();
        backfillCouponColumns();
        backfillProductReviewColumns();
    }

    private void addProductColumnsIfNeeded() {
        executeSchemaUpdate("ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price DECIMAL(10,2) DEFAULT 0.00 NOT NULL");
        executeSchemaUpdate("ALTER TABLE products ADD COLUMN IF NOT EXISTS visible BOOLEAN DEFAULT TRUE NOT NULL");
        executeSchemaUpdate("ALTER TABLE products ADD COLUMN IF NOT EXISTS sku VARCHAR(64)");
        executeSchemaUpdate("ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER DEFAULT 5 NOT NULL");
        executeSchemaUpdate("ALTER TABLE products ADD COLUMN IF NOT EXISTS reserved_stock INTEGER DEFAULT 0 NOT NULL");
        executeSchemaUpdate("CREATE UNIQUE INDEX IF NOT EXISTS idx_products_sku ON products(sku)");
    }

    private void addOrderColumnsIfNeeded() {
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_amount DECIMAL(10,2)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0.00");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code VARCHAR(64)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS alternate_phone_number VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS country VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS location_label VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method VARCHAR(255)");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMP WITH TIME ZONE");
        executeSchemaUpdate("ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancellation_reason VARCHAR(512)");
    }

    private void addCouponColumnsIfNeeded() {
        executeSchemaUpdate("ALTER TABLE coupons ADD COLUMN IF NOT EXISTS scope VARCHAR(32) DEFAULT 'ALL_PRODUCTS' NOT NULL");
        executeSchemaUpdate("ALTER TABLE coupons ADD COLUMN IF NOT EXISTS first_order_only BOOLEAN DEFAULT FALSE NOT NULL");
        executeSchemaUpdate("ALTER TABLE coupons ADD COLUMN IF NOT EXISTS one_use_per_customer BOOLEAN DEFAULT FALSE NOT NULL");
        executeSchemaUpdate("ALTER TABLE coupons ADD COLUMN IF NOT EXISTS target_category_slugs VARCHAR(1000)");
        executeSchemaUpdate("ALTER TABLE coupons ADD COLUMN IF NOT EXISTS target_product_ids VARCHAR(2000)");
    }

    private void createAddressesTableIfNeeded() {
        executeSchemaUpdate("""
            CREATE TABLE IF NOT EXISTS addresses (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                label VARCHAR(80),
                full_name VARCHAR(255) NOT NULL,
                street_address VARCHAR(255) NOT NULL,
                address_line_2 VARCHAR(255),
                city VARCHAR(120) NOT NULL,
                state VARCHAR(120) NOT NULL,
                zip_code VARCHAR(20) NOT NULL,
                country VARCHAR(120) NOT NULL,
                phone VARCHAR(40) NOT NULL,
                is_default BOOLEAN DEFAULT FALSE NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                CONSTRAINT fk_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
            )
            """);
        executeSchemaUpdate("CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id)");
    }

    private void createProductInventoryMovementsTableIfNeeded() {
        executeSchemaUpdate("""
            CREATE TABLE IF NOT EXISTS product_inventory_movements (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id BIGINT NOT NULL,
                type VARCHAR(40) NOT NULL,
                on_hand_delta INTEGER NOT NULL,
                reserved_delta INTEGER NOT NULL,
                on_hand_after INTEGER NOT NULL,
                reserved_after INTEGER NOT NULL,
                available_after INTEGER NOT NULL,
                reference_type VARCHAR(64),
                reference_id BIGINT,
                note VARCHAR(512),
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                CONSTRAINT fk_inventory_movements_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
            )
            """);
        executeSchemaUpdate("CREATE INDEX IF NOT EXISTS idx_inventory_movements_product_id_created_at ON product_inventory_movements(product_id, created_at)");
        executeSchemaUpdate("CREATE INDEX IF NOT EXISTS idx_inventory_movements_reference ON product_inventory_movements(reference_type, reference_id)");
    }

    private void createProductReviewsTableIfNeeded() {
        executeSchemaUpdate("""
            CREATE TABLE IF NOT EXISTS product_reviews (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id BIGINT NOT NULL,
                reviewer_user_id BIGINT,
                reviewer_name VARCHAR(120) NOT NULL,
                reviewer_email VARCHAR(255) NOT NULL,
                rating INTEGER NOT NULL,
                message VARCHAR(2000) NOT NULL,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                CONSTRAINT fk_product_reviews_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
                CONSTRAINT fk_product_reviews_user FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE SET NULL
            )
            """);
        executeSchemaUpdate("ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS reviewer_user_id BIGINT");
        executeSchemaUpdate("CREATE INDEX IF NOT EXISTS idx_product_reviews_reviewer_user_id ON product_reviews(reviewer_user_id)");
        executeSchemaUpdate("CREATE INDEX IF NOT EXISTS idx_product_reviews_product_id ON product_reviews(product_id)");
    }

    private void backfillProductColumns() {
        executeSchemaUpdate("UPDATE products SET cost_price = CAST(price * 0.58 AS DECIMAL(10,2)) WHERE cost_price IS NULL OR cost_price = 0");
        executeSchemaUpdate("UPDATE products SET visible = TRUE WHERE visible IS NULL");
        executeSchemaUpdate("UPDATE products SET low_stock_threshold = 5 WHERE low_stock_threshold IS NULL OR low_stock_threshold < 0");
        executeSchemaUpdate("UPDATE products SET reserved_stock = 0 WHERE reserved_stock IS NULL OR reserved_stock < 0");
        executeSchemaUpdate("UPDATE products SET sku = CONCAT('CORA-', id) WHERE sku IS NULL OR TRIM(sku) = ''");
    }

    private void backfillOrderColumns() {
        executeSchemaUpdate("UPDATE orders SET subtotal_amount = total_amount WHERE subtotal_amount IS NULL");
        executeSchemaUpdate("UPDATE orders SET discount_amount = 0.00 WHERE discount_amount IS NULL");
        executeSchemaUpdate("UPDATE orders SET payment_method = CASE WHEN payment_provider = 'COD' THEN 'COD' ELSE 'PHONEPE' END WHERE payment_method IS NULL");
    }

    private void backfillCouponColumns() {
        executeSchemaUpdate("UPDATE coupons SET scope = 'ALL_PRODUCTS' WHERE scope IS NULL");
        executeSchemaUpdate("UPDATE coupons SET first_order_only = FALSE WHERE first_order_only IS NULL");
        executeSchemaUpdate("UPDATE coupons SET one_use_per_customer = FALSE WHERE one_use_per_customer IS NULL");
    }

    private void backfillProductReviewColumns() {
        executeSchemaUpdate("""
            UPDATE product_reviews pr
            SET reviewer_user_id = (
                SELECT u.id
                FROM users u
                WHERE LOWER(u.email) = LOWER(pr.reviewer_email)
            )
            WHERE reviewer_user_id IS NULL
              AND EXISTS (
                  SELECT 1
                  FROM users u
                  WHERE LOWER(u.email) = LOWER(pr.reviewer_email)
              )
            """);
    }

    private void executeSchemaUpdate(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (RuntimeException exception) {
            log.warn("Schema repair statement failed: {}", sql, exception);
        }
    }
}
