package com.candleora.service;

import com.candleora.dto.banner.AdminFestiveBannerRequest;
import com.candleora.dto.banner.AdminFestiveBannerResponse;
import com.candleora.dto.banner.FestiveBannerPopupResponse;
import com.candleora.entity.Coupon;
import com.candleora.entity.FestiveBanner;
import com.candleora.repository.FestiveBannerRepository;
import java.time.Instant;
import java.util.List;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import org.springframework.web.server.ResponseStatusException;

@Service
@Transactional
public class FestiveBannerService {

    private final FestiveBannerRepository festiveBannerRepository;
    private final CouponService couponService;

    public FestiveBannerService(
        FestiveBannerRepository festiveBannerRepository,
        CouponService couponService
    ) {
        this.festiveBannerRepository = festiveBannerRepository;
        this.couponService = couponService;
    }

    @Transactional(readOnly = true)
    public List<AdminFestiveBannerResponse> listAdminBanners() {
        return festiveBannerRepository.findAllByOrderByPriorityDescStartTimeDescIdDesc().stream()
            .map(this::toAdminResponse)
            .toList();
    }

    @Transactional(readOnly = true)
    public AdminFestiveBannerResponse getAdminBanner(Long id) {
        FestiveBanner banner = festiveBannerRepository.findById(id)
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Festive banner not found"));
        return toAdminResponse(banner);
    }

    @Transactional(readOnly = true)
    public FestiveBannerPopupResponse getActiveBanner() {
        Instant now = Instant.now();

        return festiveBannerRepository.findAllByActiveTrueOrderByPriorityDescStartTimeAscIdDesc().stream()
            .filter(banner -> !now.isBefore(banner.getStartTime()) && now.isBefore(banner.getEndTime()))
            .findFirst()
            .map(this::toPopupResponse)
            .orElse(null);
    }

    public AdminFestiveBannerResponse createBanner(AdminFestiveBannerRequest request) {
        FestiveBanner banner = new FestiveBanner();
        applyRequest(banner, request);
        return toAdminResponse(festiveBannerRepository.save(banner));
    }

    public AdminFestiveBannerResponse updateBanner(Long id, AdminFestiveBannerRequest request) {
        FestiveBanner banner = festiveBannerRepository.findById(id)
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Festive banner not found"));

        applyRequest(banner, request);
        return toAdminResponse(festiveBannerRepository.save(banner));
    }

    public void deleteBanner(Long id) {
        FestiveBanner banner = festiveBannerRepository.findById(id)
            .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Festive banner not found"));

        if (banner.isAutoGenerateCoupon()) {
            couponService.deactivateCoupon(banner.getCouponId());
        }

        festiveBannerRepository.delete(banner);
    }

    private void applyRequest(FestiveBanner banner, AdminFestiveBannerRequest request) {
        validateRequest(request);

        Long previousCouponId = banner.getCouponId();
        boolean previouslyAutoGenerated = banner.isAutoGenerateCoupon();

        Coupon linkedCoupon;
        if (request.autoGenerateCoupon()) {
            linkedCoupon = couponService.syncAutoGeneratedCoupon(
                previouslyAutoGenerated ? previousCouponId : null,
                request.title(),
                request.discountType(),
                request.discountValue(),
                request.maxDiscount(),
                request.minOrderAmount(),
                request.startTime(),
                request.endTime(),
                request.active()
            );
        } else {
            linkedCoupon = couponService.findCouponByCodeOrThrow(request.existingCouponCode());

            if (previouslyAutoGenerated && previousCouponId != null && !previousCouponId.equals(linkedCoupon.getId())) {
                couponService.deactivateCoupon(previousCouponId);
            }
        }

        banner.setTitle(StringUtils.trimWhitespace(request.title()));
        banner.setDescription(trimToNull(request.description()));
        banner.setImageUrl(StringUtils.trimWhitespace(request.imageUrl()));
        banner.setRedirectUrl(trimToNull(request.redirectUrl()));
        banner.setCtaLabel(trimToNull(request.ctaLabel()));
        banner.setAutoGenerateCoupon(request.autoGenerateCoupon());
        banner.setCouponId(linkedCoupon.getId());
        banner.setCouponCode(linkedCoupon.getCode());
        banner.setDiscountType(linkedCoupon.getType());
        banner.setDiscountValue(linkedCoupon.getValue());
        banner.setMaxDiscount(linkedCoupon.getMaxDiscount());
        banner.setMinOrderAmount(linkedCoupon.getMinOrderAmount());
        banner.setActive(request.active());
        banner.setShowOnce(request.showOnce());
        banner.setPriority(Math.max(0, request.priority()));
        banner.setStartTime(request.startTime());
        banner.setEndTime(request.endTime());
    }

    private void validateRequest(AdminFestiveBannerRequest request) {
        if (!StringUtils.hasText(request.title())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Banner title is required");
        }

        if (!StringUtils.hasText(request.imageUrl())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Banner image is required");
        }

        if (request.startTime() == null || request.endTime() == null) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Start and end time are required");
        }

        if (!request.endTime().isAfter(request.startTime())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Banner end time must be after the start time");
        }

        if (request.autoGenerateCoupon()) {
            if (request.discountType() == null) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Discount type is required for auto-generated coupons");
            }

            if (request.discountValue() == null) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Discount value is required for auto-generated coupons");
            }
        } else if (!StringUtils.hasText(request.existingCouponCode())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Choose an existing coupon to link this banner");
        }
    }

    private String trimToNull(String value) {
        if (!StringUtils.hasText(value)) {
            return null;
        }

        return value.trim();
    }

    private AdminFestiveBannerResponse toAdminResponse(FestiveBanner banner) {
        return new AdminFestiveBannerResponse(
            banner.getId(),
            banner.getTitle(),
            banner.getDescription(),
            banner.getImageUrl(),
            banner.getRedirectUrl(),
            banner.getCtaLabel(),
            banner.isAutoGenerateCoupon(),
            banner.getCouponId(),
            banner.getCouponCode(),
            banner.getDiscountType(),
            banner.getDiscountValue(),
            banner.getMaxDiscount(),
            banner.getMinOrderAmount(),
            banner.isActive(),
            banner.isShowOnce(),
            banner.getPriority(),
            banner.getStartTime(),
            banner.getEndTime(),
            banner.getCreatedAt(),
            banner.getUpdatedAt()
        );
    }

    private FestiveBannerPopupResponse toPopupResponse(FestiveBanner banner) {
        return new FestiveBannerPopupResponse(
            banner.getId(),
            banner.getTitle(),
            banner.getDescription(),
            banner.getImageUrl(),
            banner.getRedirectUrl(),
            StringUtils.hasText(banner.getCtaLabel()) ? banner.getCtaLabel() : "Apply offer",
            banner.getCouponCode(),
            banner.isShowOnce(),
            banner.getEndTime()
        );
    }
}
