package com.candleora.entity;

public enum InventoryMovementType {
    MANUAL_ADJUSTMENT,
    RESERVATION_CREATED,
    RESERVATION_RELEASED,
    ORDER_COMMITTED,
    DIRECT_SALE_COMMITTED,
    ORDER_RESTOCKED,
    REPLACEMENT_RESERVED,
    REPLACEMENT_RELEASED,
    REPLACEMENT_COMMITTED
}
