CREATE TABLE IF NOT EXISTS order_tracking_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    detail VARCHAR(1000),
    event_timestamp TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_tracking_events_order_status
    ON order_tracking_events(order_id, status);
CREATE INDEX IF NOT EXISTS idx_order_tracking_events_order_event_timestamp
    ON order_tracking_events(order_id, event_timestamp DESC);
